name: Coverage

on:
  push:
    branches:
      - '*'
  repository_dispatch:
    types: manual-trigger

jobs:
  run_coverage:
    if: contains(toJson(github.event.commits), '[skip ci]') == false && contains(toJson(github.event.commits), '[skip github]') == false

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
        pip list
        echo "PYTHONPATH=home/runner/work/psautohint/build/lib" >> $GITHUB_ENV

    - name: Generate and upload Python and C coverage
      env:
        CFLAGS: '--coverage'
      run: |
        pip install pytest==5.4.3 pytest-cov pytest-xdist==1.34.0
        python setup.py build --build-base build --build-platlib build/lib
        python setup.py install
        python -m pytest --cov=psautohint --cov-report=xml -n auto
        bash <(curl -s https://codecov.io/bash) -y .codecov.yml
