name: Test and Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches: [master]
  repository_dispatch:
    types: manual-trigger

jobs:
  run_tests:
    if: contains(toJson(github.event.commits), '[skip ci]') == false && contains(toJson(github.event.commits), '[skip github]') == false

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.8

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
        
    - name: Lint with flake8 (only Ubuntu/Python 3.9)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
      run: |
        pip install flake8
        flake8 --config=setup.cfg --count --show-source --statistics

    - name: Test with tox (except Ubuntu/Python 3.7)
      # not in love with the following syntax, but it works,
      # whereas "! (condition)" does NOT
      if: (matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7') == false 
      run: |
        tox -e py-cov

  build_wheels:
    needs: run_tests
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Use MSBuild (Windows only)
        uses: microsoft/setup-msbuild@v1.0.2
        if: matrix.os == 'windows-latest'
    
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel
      
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir dist
        env: 
          CIBW_BUILD: "cp3?-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_SKIP: "pp* cp35* cp*win32 cp*manylinux_i686 cp*manylinux_aarch64 cp*manylinux_ppc64le cp*manylinux_s390x"
          CIBW_ENVIRONMENT: "CFLAGS='-g0'"
      
      - name: Build sdist
        run: |
          python setup.py sdist
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      
      - name: Publish package to PyPI
        run: |
          pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

      - name: Create release
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Attach sdist to release
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit $(find dist -type f -name "*.zip" -printf "-a %p ") -m "" "$tag_name"
